### ISSUE TITLE
Another Shiny issue. Nothing displayed.

### ISSUE THREAD

**Issue by Vongo** [timelyportfolio/explodingboxplotR#4]
Hi, I have recently discovered this package, and I am pretty fond of it.

Unfortunately, I can't manage to make it work together with Shiny.

Here is the dummy code I tried :

```
library(shiny)
library(explodingboxplotR)
data(iris)

 ui <- fluidPage(
    titlePanel("Exploding Boxplot Test"),
    mainPanel(
        exploding_boxplotOutput("box")
    )
)

server <- function(input, output, session) {
    output$box <- renderExploding_boxplot({
        print("ping")
        exploding_boxplot(
            data.frame(
                rowname = rownames(iris),
                iris,
                stringsAsFactors = FALSE
            ),
            y = "Sepal.Length",
            group = "Species",
            color = "Species",
            label = "Species"
        )
    })
}

shinyApp(ui,server)
```

When I launch it, nothing seems to happen (the Shiny server starts with the title on the page, but that's it).

> sessionInfo()
> R version 3.2.3 (2015-12-10)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 14.04.3 LTS
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
>  [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=en_US.UTF-8
>  [7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C
> [11] LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base
> 
> other attached packages:
> [1] explodingboxplotR_0.0.1 shiny_0.13.0
> 
> loaded via a namespace (and not attached):
>  [1] htmlwidgets_0.5.2 R6_2.1.2          tools_3.2.3       htmltools_0.3
>  [5] yaml_2.1.13       Rcpp_0.12.3       jsonlite_0.9.19   digest_0.6.9
>  [9] xtable_1.8-2      httpuv_1.3.3      mime_0.4

**Comment by timelyportfolio** [comment]
thanks for report.  Glad you like it.  What happens when you run without `Shiny`?

```
exploding_boxplot(
            data.frame(
                rowname = rownames(iris),
                iris,
                stringsAsFactors = FALSE
            ),
            y = "Sepal.Length",
            group = "Species",
            color = "Species",
            label = "Species"
        )
```

**Comment by Vongo** [comment]
Well, it opens a window in my browser with the fully-functional exploding boxplot.
Sorry, I should have stated it before.
Note that I also have opened a question on [StackOverflow](http://stackoverflow.com/questions/35293216/cant-display-exploding-boxplot-in-shiny) about it.

**Comment by timelyportfolio** [comment]
Sorry, I just realized I never made the change in `master` to fix this and #2. Am fixing now. Sorry again.

**Comment by Vongo** [comment]
Thanks a lot !!

**Comment by timelyportfolio** [comment]
@Vongo, can you test now with the new `master`?

**Comment by Vongo** [comment]
Yay, it works perfectly ! Thank you very much for being so reactive :-)
Kudos !

**Comment by timelyportfolio** [comment]
Great to hear!  Speaking of `reactive`, if you think you might want something like https://twitter.com/timelyportfolio/status/685555165236178945 let me know.  Waiting on this to stabilize in `htmlwidgets`.
